spring.application.name=ordersystem


server.port=8080

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/product_order?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LOGGING
logging.level.org.springframework=INFO
logging.level.com.department=DEBUG



